### ISSUE TITLE
Bake in CakePHP 4.0.7 

### ISSUE THREAD

**Issue by reiserfs** [maiconpinto/cakephp-adminlte-theme#105]
Hello, i am trying to bake my template, but i got this

$ bin/cake bake template -f -t AdminLTE Login
Error: "AdminLTE" is not a valid value for --theme. Please use one of "Bake, Migrations"

checked loaded plugins
$ bin/cake plugin loaded
AdminLTE
Bake
Cake/TwigView
DebugKit
Migrations

Dont know what i am missing.
CakePHP 4.0.7

**Comment by hassisto** [comment]
Same problem also with previous version of CakePHP 4.x

**Comment by eafrade** [comment]
Hello

Sorry for the English. I am Brazilian and I used a translator to write the text.

I had the same problem. I'm using linux and found that the bake folder in "vendor/maiconpinto/cakephp-adminlte-theme/templates/Bake/"
it started with a capital "B". I changed it to lowercase "b" and the problem was solved.

Perhaps it is the same case for you.
CakePHP 4.0.8
